export const actionTypesAuth = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USER_LOGOUT',

    AUTH_REQUEST: 'USER_AUTH_REQUEST',
    AUTH_SUCCESS: 'USER_AUTH_SUCCESS',
    AUTH_FAILURE: 'USER_AUTH_FAILURE',

    CONFIRM_EMAIL_REQUEST: 'EMAIL_CONFIRM_REQUEST',
    CONFIRM_EMAIL_SUCCESS: 'EMAIL_CONFIRM_SUCCESS',
    CONFIRM_EMAIL_FAILURE: 'EMAIL_CONFIRM_FAILURE',
};
