export const actionTypesPopups = {
    REGISTRATION_SHOW: 'POPUP_REGISTRATION_SHOW',
    REGISTRATION_EARLY_SHOW: 'POPUP_REGISTRATION_EARLY_SHOW',

    SIGNIN_SHOW: 'POPUP_SIGNIN_SHOW',

    CHALLENGE_SHOW: 'POPUP_CHALLENGE_SHOW',

    INVITE_SHOW: 'POPUP_INVITE_SHOW',

    POPUPS_HIDE: 'POPUP_HIDE',
};
